name: Automat
on:
  push:
    branches:
    - production
  workflow_dispatch:
jobs:
  buid-and-push:
    runs-on: Ubuntu-late

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Docker build
      uses: docker/setup-buildx-action@v1

    - name: Docker Hub
      uses: docker/login-actions/checkout@v1

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        contntex: .
        push: true
        tags: ${{secrets.DOCKER_USERNAME}}/
